In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
dir = "/content/drive/MyDrive/558_Career_KG/"

Mounted at /content/drive

In [23]:
all_titles = pd.read_csv(dir+"Entity Linking/combined_df.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [24]:
all_titles.head()

,Unnamed: 0,id,name_x,isSupervisor,indeed_name,JD_x,responsibility,salary_x,skills_x,name_y,glassdoor_name,JD_y,salary_y,related_titles,skills_y,skills
0,0,ET4A446A1A5F6142AD,.NET Application Architect,False,.NET Developer,A .NET developer is an information technology ...,Designing interfaces for client use\nIdentifyi...,102973 YEARLY,".NET, .NET Core, APIs, ASP.NET, Agile, Angular...",.NET Application Architect,.NET Application Architect,A Software Architect serves as the team leader...,"$174,308 /yr",Enterprise Architect; Systems Architect; Infra...,"MS SQL Server, Javascript, Drupal, Cloud, Fram...",".NET, .NET Core, APIs, ASP.NET, AWS, Agile, An..."
1,1,ETB5E3860B8B9A9755,.NET Architect,False,Software Architect,Software architects are expert software design...,Perform research for projects to determine the...,134961 YEARLY,NaN,.NET Architect,.NET Architect,"Architects plan, develop, and implement design...","$170,168 /yr",Architectural Drafter; Architectural Designer;...,"Microsoft Cloud, Azure, Restful APIS, Javascri...","Active Directory, Azure, Frameworks, Javascrip..."
2,2,ETEB3BB8E555C79368,.NET Developer,False,.NET Developer,A .NET developer is an information technology ...,Designing interfaces for client use\nIdentifyi...,102973 YEARLY,".NET, .NET Core, APIs, ASP.NET, Agile, Angular...",.NET Developer,.NET Developer,Web developers work within the design code and...,"$105,292 /yr",Software Engineer; Software Developer; Front E...,".NET Framework, javascript/jquery, SQL Server,...",".NET, .NET Core, .NET Framework, APIs, ASP Net..."
3,3,ETB3859094FF2DD443,.NET Front End Developer,False,Front End Developer,Front end developers implement the visual and ...,Designing or editing websites or web applicati...,101870 YEARLY,", AJAX, APIs, AWS, Agile, Angular, Azure, Boot...",.NET Front End Developer,Front End Developer,"Front end engineers plan, design, build, and i...","$85,016 /yr",Software Engineer; Software Developer; Mobile ...,"HTML AND CSS, javascript/jquery, angular.js, F...","AJAX, APIs, AWS, Agile, Angular, Azure, Bootst..."
4,4,ETE906C8A7B45816CC,.NET Full Stack Developer,False,Full Stack Developer,A full stack developer develops and deploys th...,Converting the elements of web designs into ex...,101528 YEARLY,"APIs, AWS, Agile, Angular, Azure, C#, CI/CD, C...",.NET Full Stack Developer,.NET Full Stack Developer,Full-stack engineers are senior-level computer...,"$112,176 /yr",Software Engineer; Software Developer; Front E...,"Javascript, HTML AND CSS, Node.js, Back End, R...",".NET, APIs, AWS, Agile, Angular, Azure, Back E..."

In [25]:
len(all_titles)

61858

# Filter Uncommon Titles

## Filter by non Nan Skills

In [26]:
all_titles = all_titles[(~all_titles["skills"].isnull())]

## Filter by Intersection of skills

In [27]:
all_titles[(all_titles["skills"].isnull())&(~all_titles["skills_y"].isnull())]

Empty DataFrame
Columns: [Unnamed: 0, id, name_x, isSupervisor, indeed_name, JD_x, responsibility, salary_x, skills_x, name_y, glassdoor_name, JD_y, salary_y, related_titles, skills_y, skills]
Index: []

## Combine Columns

In [28]:
all_titles["description"] = all_titles["JD_x"]+"\n"+all_titles["JD_y"]

In [29]:
def x_type(a):
  if type(a) is not float:
    if a.endswith("YEARLY"):
      return "Yearly"
    else:
      return "Hourly"
  return a

def y_type(a):
  if type(a) is not float:
    if a.endswith("/yr"):
      return "Yearly"
    else:
      return "Hourly"
  return a

In [30]:
all_titles["salaryType_x"] = all_titles["salary_x"].apply(x_type)

In [31]:
all_titles["salaryType_y"] = all_titles["salary_y"].apply(y_type)

In [32]:
def estimate_salaryYearly(x):
  if type(x.salaryType_y) is not float:
      return float("".join(re.findall(r'\d+',x.salary_y)))
  elif x.salaryType_x == "Yearly":
    try:
      return float("".join(re.findall(r'\d+',x.salary_x)))
    except:
      print(x.salary_x)
      return np.nan
  else:
    return np.nan

def estimate_salaryHourly(x):
  if x.salaryType_x == "Hourly":
    try:
      return float(".".join(re.findall(r'\d+',x.salary_x)))
    except:
      return np.nan
  else:
    return np.nan

In [33]:
all_titles["salaryYearly"] = all_titles.apply(estimate_salaryYearly,axis=1)

 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY
 YEARLY

In [34]:
all_titles["salaryHourly"] = all_titles.apply(estimate_salaryHourly,axis=1)

In [35]:
all_titles.columns

Index(['Unnamed: 0', 'id', 'name_x', 'isSupervisor', 'indeed_name', 'JD_x',
       'responsibility', 'salary_x', 'skills_x', 'name_y', 'glassdoor_name',
       'JD_y', 'salary_y', 'related_titles', 'skills_y', 'skills',
       'description', 'salaryType_x', 'salaryType_y', 'salaryYearly',
       'salaryHourly'],
      dtype='object')

In [36]:
def name_selection(x):
  if type(x.name_x) != float:
    return x.name_x
  else:
    return x.name_y

In [37]:
all_titles["name"] = all_titles.apply(name_selection, axis = 1)

# Rename and Output

In [38]:
all_titles[["id","name","description","responsibility","salaryYearly","salaryHourly","related_titles","skills"]].to_csv(dir+"KG Construct/all_titles_processed.csv", index=False)

In [39]:
all_titles[["id","name"]].to_csv(dir+"Entity Linking/title_id_link.csv", index=False)